# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Disturbed Systems Blog
email: jannnnna@gmx.de
description: > # this means to ignore newlines until "baseurl:"
    A collection of projects of our team.
baseurl: "/disturbed-systems" # the subpath of your site, e.g. /blog
url: "http://jtraue.github.io/disturbed-systems" # the base hostname & protocol for your site
github_username:  jtraue

# Build settings
markdown: kramdown
